server {
    listen 80;
    resolver 127.0.0.11 valid=10s;

    # Auth
    location = /_auth {
        internal;
        set $core_verify http://core:8000/api/verify;
        proxy_pass              $core_verify;
        proxy_pass_request_body off;
        proxy_set_header        Content-Length "";
        proxy_set_header        Authorization $http_authorization;
        proxy_set_header        Cookie $http_cookie;
    }

    # API
    location /api/ {
        auth_request /_auth;
        auth_request_set $user_id   $upstream_http_x_user_id;
        auth_request_set $user_name $upstream_http_x_user_username;
        proxy_set_header X-User-Id       $user_id;
        proxy_set_header X-User-Username $user_name;

        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
    }

    # Static files
    location /static/ {
        alias /app/staticfiles/;
        expires 30d;
        access_log off;
    }

    location /media/ {
        alias /app/media/;
        expires 30d;
        access_log off;
    }

    # Main site
    location / {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    error_page 401 = @needs_login;
    location @needs_login { return 302 http://localhost:8000/login; }
}