# Generated by Django 5.2.15 on 2026-06-30 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workouthistory',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
